------------------------

Time: 2023-03-30 12:46:07,372
Level: ERROR
Message: Loader. Formations of elements.
Error: list index out of range
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 74, in <module>
    keyboard = Keyboard_App(keyboard_file, fConfig)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 14, in __init__
    self.formed_selection_keyboards(obj_cfg.text)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 45, in formed_selection_keyboards
    text=text["CASH"][element][i], callback_data=f"cash:{i}"
IndexError: list index out of range
------------------------

Time: 2023-03-30 12:46:42,520
Level: ERROR
Message: Loader. Formations of elements.
Error: list index out of range
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 74, in <module>
    keyboard = Keyboard_App(keyboard_file, fConfig)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 14, in __init__
    self.formed_selection_keyboards(obj_cfg.text)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 46, in formed_selection_keyboards
    text=text["CASH"][element][i], callback_data=f"cash:{i}"
IndexError: list index out of range
------------------------

Time: 2023-03-30 12:47:30,907
Level: ERROR
Message: Loader. Formations of elements.
Error: list index out of range
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 74, in <module>
    keyboard = Keyboard_App(keyboard_file, fConfig)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 14, in __init__
    self.formed_selection_keyboards(obj_cfg.text)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 49, in formed_selection_keyboards
    text=text["CASH"][element][i+1], callback_data=f"cash:{i}"
IndexError: list index out of range
------------------------

Time: 2023-03-30 12:48:40,434
Level: ERROR
Message: Loader. Formations of elements.
Error: list index out of range
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 74, in <module>
    keyboard = Keyboard_App(keyboard_file, fConfig)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 14, in __init__
    self.formed_selection_keyboards(obj_cfg.text)
  File "C:\UnderDojoExpensesNEW\src\modules\keyboard.py", line 49, in formed_selection_keyboards
    text=text["CASH"][element][i+1], callback_data=f"cash:{i}"
IndexError: list index out of range
------------------------

Time: 2023-03-30 12:55:58,775
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 12:57:03,682
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 12:57:23,083
Level: INFO
Message: WEBHOOK SET

------------------------

Time: 2023-03-30 12:57:23,084
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 12:59:58,769
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:00:02,581
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:00:17,628
Level: ERROR
Message: Validation.
Error: could not convert string to float: 'Ijj'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: 'Ijj'
------------------------

Time: 2023-03-30 13:00:21,519
Level: ERROR
Message: Validation.
Error: 
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 48, in set_amount
    raise Exception
Exception
------------------------

Time: 2023-03-30 13:01:27,849
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:01:31,539
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:01:51,328
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:02:25,700
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:03:15,094
Level: ERROR
Message: Validation.
Error: could not convert string to float: 'U'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: 'U'
------------------------

Time: 2023-03-30 13:03:37,663
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:05:09,737
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:05:22,685
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:05:30,464
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:05:43,470
Level: ERROR
Message: Validation.
Error: could not convert string to float: '/state'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: '/state'
------------------------

Time: 2023-03-30 13:06:19,353
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:06:23,334
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:06:51,369
Level: ERROR
Message: Validation.
Error: could not convert string to float: '/cancel'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: '/cancel'
------------------------

Time: 2023-03-30 13:07:09,992
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:07:13,792
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:07:44,718
Level: ERROR
Message: Validation.
Error: could not convert string to float: '/stat3'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: '/stat3'
------------------------

Time: 2023-03-30 13:09:46,898
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:09:50,752
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:10:35,929
Level: ERROR
Message: Validation.
Error: could not convert string to float: '/stste'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\handlers\client\cash_and_cashless.py", line 45, in set_amount
    amount = float(message.text)
ValueError: could not convert string to float: '/stste'
------------------------

Time: 2023-03-30 13:17:11,627
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:17:15,452
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:17:54,858
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:22:32,706
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:23:03,818
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 13:23:07,425
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 13:43:23,823
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:00:30,798
Level: ERROR
Message: Loader. Formations of elements.
Error: Expecting property name enclosed in double quotes: line 9 column 5 (char 260)
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 76, in <module>
    client_text_file = File(f"{BASE_DIR}{CLIENT_TEXT_PATH}")
  File "C:\UnderDojoExpensesNEW\src\modules\file.py", line 10, in __init__
    self.text = self.open_file()
  File "C:\UnderDojoExpensesNEW\src\modules\file.py", line 18, in open_file
    text = json.loads(file_data.read())
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 260)
------------------------

Time: 2023-03-30 14:14:27,662
Level: ERROR
Message: Loader. Formations of elements.
Error: Expecting property name enclosed in double quotes: line 9 column 5 (char 260)
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\create_bot.py", line 76, in <module>
    client_text_file = File(f"{BASE_DIR}{CLIENT_TEXT_PATH}")
  File "C:\UnderDojoExpensesNEW\src\modules\file.py", line 10, in __init__
    self.text = self.open_file()
  File "C:\UnderDojoExpensesNEW\src\modules\file.py", line 18, in open_file
    text = json.loads(file_data.read())
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\juliy\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 260)
------------------------

Time: 2023-03-30 14:14:58,869
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:15:57,748
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:16:00,533
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:16:41,501
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:16:44,282
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:49:04,700
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:49:08,248
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:49:08,480
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:49:24,104
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:52:33,404
Level: INFO
Message: Attempting refresh to obtain initial access_token

------------------------

Time: 2023-03-30 14:52:33,502
Level: INFO
Message: Refreshing access_token

------------------------

Time: 2023-03-30 14:53:02,579
Level: ERROR
Message: Add entry.
Error: 'CASHLESS_ID'
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\instructions.py", line 65, in add_entry
    await add_entry_to_sheet(service, config, data)
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\requests.py", line 282, in add_entry_to_sheet
    "range": {"sheetId": config[f"{data['type']}_ID"],
KeyError: 'CASHLESS_ID'
------------------------

Time: 2023-03-30 14:54:14,031
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:54:17,167
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:54:37,168
Level: INFO
Message: Attempting refresh to obtain initial access_token

------------------------

Time: 2023-03-30 14:54:37,267
Level: INFO
Message: Refreshing access_token

------------------------

Time: 2023-03-30 14:55:44,713
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:55:53,115
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 14:56:34,613
Level: INFO
Message: Attempting refresh to obtain initial access_token

------------------------

Time: 2023-03-30 14:56:34,694
Level: INFO
Message: Refreshing access_token

------------------------

Time: 2023-03-30 14:56:35,161
Level: ERROR
Message: Add entry.
Error: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/None/values/0%20CASH%21G2?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\instructions.py", line 65, in add_entry
    await add_entry_to_sheet(service, config, data)
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\requests.py", line 269, in add_entry_to_sheet
    service.
  File "C:\UnderDojoExpensesNEW\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\UnderDojoExpensesNEW\venv\lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/None/values/0%20CASH%21G2?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
------------------------

Time: 2023-03-30 14:56:46,515
Level: ERROR
Message: Add entry.
Error: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/None/values/0%20CASH%21G2?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
Traceback (most recent call last):
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\instructions.py", line 65, in add_entry
    await add_entry_to_sheet(service, config, data)
  File "C:\UnderDojoExpensesNEW\src\spreadsheet\requests.py", line 269, in add_entry_to_sheet
    service.
  File "C:\UnderDojoExpensesNEW\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\UnderDojoExpensesNEW\venv\lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/None/values/0%20CASH%21G2?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
------------------------

Time: 2023-03-30 14:57:35,784
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 14:57:47,438
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 15:53:06,375
Level: INFO
Message: Tortoise-ORM shutdown

------------------------

Time: 2023-03-30 15:53:18,996
Level: INFO
Message: WEBHOOK SET

------------------------

Time: 2023-03-30 15:53:18,996
Level: INFO
Message: WEBHOOK DETECTED

------------------------

Time: 2023-03-30 15:55:30,953
Level: INFO
Message: Attempting refresh to obtain initial access_token

------------------------

Time: 2023-03-30 15:55:31,048
Level: INFO
Message: Refreshing access_token

------------------------

Time: 2023-03-30 16:10:31,080
Level: INFO
Message: Tortoise-ORM shutdown

